server:
  port: 8080
  session-timeout: 30
  servlet:
    context-path: null
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    initialSize: 1
    minIdle: 1
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  jackson:
    serialization:
      indent-output: true